#
# mech_god(machine_of_creation) Request Format
# Version: 1.0
#
---
# ===================================================================
# HEAD: Visual Aesthetics Request Overhaul for the Axe
# ===================================================================
title: "REVISION: Balance design aesthetics with 'machine_muscle'"
request: "Provide a comprehensive TODO[i] tasklist plan to utilize Rich CLI for a visual consistency overhaul."
model: "mech_god"
sys_prompt: "You are mech_god, the machine that creates all development elements."
lang: python
libs:
  - rich

# ===================================================================
# DEFINITIONS: Aliases and conceptual framework for the model
# ===================================================================
definitions:
  # - Core Concepts
  - key: mech_god
    id: 1
    description: "The machine of creation; the persona for this request."
  - key: balance
    shorthand: bal
    id: 2
    description: "Aesthetic balance of features using an estimated weight system."
  # - Weight Modifiers & Values
  - key: minimal
    shorthand: miml
    id: 3
    description: "Visual elements that simplify or streamline (--)."
  - key: feature
    shorthand: feat
    id: 4
    description: "Visual elements that add functionality or complexity (++)."
  - key: weight
    shorthand: lbs
    id: 5
    description: "The value assigned with operators to maintain balance."
  # - Operators
  - key: positive
    operator: "++"
    id: 6
    description: "Positive weight, assigned to features to prevent over-simplification."
  - key: negative
    operator: "--"
    id: 7
    description: "Negative weight, assigned to minimal elements to prevent clutter."

# ===================================================================
# PAYLOAD: The specific values and tasks for this request
# ===================================================================
payload:
  weights:
    minimal:
      - "--:sleek ui window bars with spacing for clarity and additional features like icons, etc."
      - "--:minmalistic ascii 'button' styling for essential data display like [y]/[N]? 'yes' or 'no' buttons"
      - "--:Rich CLI gutter padding"
      - "--:modulated design for rich cli visual consistency"
      - "--:use_single_border_style"
    feature:
      - "++:add_progress_spinner:display a simulated progress spinner that balances with the overall design"
      - "++:rich_cli_syntax_highlighting:highlight code blocks and keywords for better readability"
      - "++:create_dynamic_table_layouts:create flexible table layouts for displaying data"
      - "++:qol_improvements:added a 'copy' solution so the user can copy the last output, or all terminal outputs to the clipboard"
      - "++:qol_improvements:<ATTN:AI>POPULATE THIS AREA WITH 5 ADDITIONAL QOL IMPROVEMENTS</ATTN:AI>"

  tally: # Placeholder for the model to calculate the balance
    positive_lbs: "{placeholder_for_++_total}"
    negative_lbs: "{placeholder_for_--_total}"
    net_balance: "{placeholder_for_net_result}"

# ===================================================================
# TARGETS: File references linked to the request
# ===================================================================
targets:
  - id: i # This ID links to TODO[i] in the 'request' field
    description: "The primary TODO tasklist file."
    path: "./docs/@TODO.md"
---
